version: '3.8'

services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chat_system_challenge_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=password"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6.2

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: chat_system_challenge_development
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      REDIS_HOST: redis

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: chat_system_challenge_development
      DATABASE_USER: db_admin
      DATABASE_PASSWORD: dbadmin123
      REDIS_HOST: redis

volumes:
  db_data:
