recalculate_counts:
  cron: "0 * * * *" # Every minute
  class: 'RecalculateCountsJob'
  queue: default
  description: 'Recalculate the chats_count and messages_count for all applications and chats every hour'
